version: "3.8"
services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - target: 80
        published: 80
    volumes: 
      - type: bind
        source: ./nginx.conf
        target: /etc/nginx/nginx.conf

  front-end:
    image: jayrowlands/front-end:latest
    container_name: front-end
    build: ./front-end
  service2:
    image: jayrowlands/service2:latest
    container_name: service2-api
    build: ./service2-api
    deploy:
      replicas: 3
  service3:
    image: jayrowlands/service3:latest
    container_name: service3-api
    build: ./service3-api
    deploy:
      replicas: 3
  service4:
    image: jayrowlands/service4:latest
    container_name: service4-api
    build: ./service4-api
    deploy:
      replicas: 3 